name: GCP Secret Manager API
description: 'Automates the retrieval of environment secrets from GCP Secret Manager API'

inputs:
  GCP_SA_KEY:
    description: 'GCP Service Account Key (JSON)'
    required: true

  secrets:
    description: 'CSV list of secrets to pull from LastPass'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GCP_SA_KEY }}
    - ${{ inputs.secrets }}
